// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getRequest } from '@tanstack/react-start/server'
import { createClient } from '@supabase/supabase-js'
import type { Database } from './types'



function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

// Two-step verification (MFA) — see the check in requireSupabaseAuth below.
// Whether a user has an authenticator set up isn't in their token, so it's
// looked up from Supabase and remembered briefly per Worker isolate: most
// requests come from password-only (aal1) users without MFA, and they
// shouldn't pay a Supabase round trip on every server call.
const MFA_STATUS_TTL_MS = 60_000;
const mfaStatusCache = new Map<string, { hasMfa: boolean; expires: number }>();

async function userHasMfa(
  supabase: ReturnType<typeof createClient<Database>>,
  token: string,
  userId: string,
): Promise<boolean> {
  const cached = mfaStatusCache.get(userId);
  if (cached && cached.expires > Date.now()) return cached.hasMfa;
  const { data, error } = await supabase.auth.getUser(token);
  if (error || !data.user) {
    throw new Error('Unauthorized: Invalid token');
  }
  const hasMfa = (data.user.factors ?? []).some((factor) => factor.status === 'verified');
  if (mfaStatusCache.size > 5000) mfaStatusCache.clear();
  mfaStatusCache.set(userId, { hasMfa, expires: Date.now() + MFA_STATUS_TTL_MS });
  return hasMfa;
}

export const requireSupabaseAuth = createMiddleware({ type: 'function' }).server(
  async ({ next }) => {
    
    const SUPABASE_URL = process.env['SUPABASE_URL'];
    const SUPABASE_PUBLISHABLE_KEY = process.env['SUPABASE_PUBLISHABLE_KEY'];

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      const missing = [
        ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
        ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
      ];
      const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
      console.error(`[Supabase] ${message}`);
      throw new Error(message);
    }
    
    const request = getRequest();

    if (!request?.headers) {
      throw new Error('Unauthorized: No request headers available');
    }

    const authHeader = request.headers.get('authorization');

    if (!authHeader) {
      throw new Error('Unauthorized: No authorization header provided');
    }

    if (!authHeader.startsWith('Bearer ')) {
      throw new Error('Unauthorized: Only Bearer tokens are supported');
    }

    const token = authHeader.replace('Bearer ', '');
    if (!token) {
      throw new Error('Unauthorized: No token provided');
    }

    if (token.split('.').length !== 3) {
      throw new Error('Unauthorized: Invalid token');
    }

    const supabase = createClient<Database>(
      SUPABASE_URL!,
      SUPABASE_PUBLISHABLE_KEY!,
      {
        global: {
          fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY!),
          headers: {
            Authorization: `Bearer ${token}`,
          },
        },
        auth: {
          storage: undefined,
          persistSession: false,
          autoRefreshToken: false,
        },
      }
    );

    const { data, error } = await supabase.auth.getClaims(token);
    if (error || !data?.claims) {
      throw new Error('Unauthorized: Invalid token');
    }

    if (!data.claims.sub) {
      throw new Error('Unauthorized: No user ID found in token');
    }

    // [edited by hand — keep when regenerating] A user with two-step
    // verification on must have entered their code (aal2). A password-only
    // (aal1) token for such a user is refused, so the code prompt in the
    // browser can't be skipped by calling these server functions directly.
    // (The Medusa backend's Supabase auth provider enforces the same rule.)
    if (data.claims['aal'] !== 'aal2' && (await userHasMfa(supabase, token, data.claims.sub))) {
      throw new Error('Unauthorized: Two-step verification required');
    }

    return next({
      context: {
        supabase,
        userId: data.claims.sub,
        claims: data.claims,
        // The raw Supabase access token, so a server function can present
        // it to the Medusa backend's `supabase` auth provider and exchange
        // it for a Medusa customer session (see lib/medusa/auth.server.ts).
        accessToken: token,
      },
    });
  },
);
